// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-members.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-members.ts
var list_members_default = defineTool({
  name: "list_members",
  title: "List gym members",
  description: "List the signed-in gym owner's members (admissions), optionally filtered by payment status or a name/phone search.",
  inputSchema: {
    status: z.enum(["all", "paid", "unpaid"]).optional().describe("Filter by membership payment status. Defaults to all."),
    search: z.string().optional().describe("Match against member name or phone."),
    limit: z.number().int().optional().describe("Max members to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("admissions").select("id, name, phone, status, join_date, age, height, weight, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (status && status !== "all") query = query.eq("status", status);
    if (search?.trim())
      query = query.or(`name.ilike.%${search.trim()}%,phone.ilike.%${search.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { members: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/add-member.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_member_default = defineTool2({
  name: "add_member",
  title: "Add gym member",
  description: "Register a new gym member (admission) for the signed-in gym owner. Name and phone are required.",
  inputSchema: {
    name: z2.string().describe("Member full name."),
    phone: z2.string().describe("10-digit phone number."),
    join_date: z2.string().optional().describe("Date of joining as YYYY-MM-DD."),
    age: z2.number().int().optional().describe("Member age in years."),
    height: z2.number().optional().describe("Height in cm."),
    weight: z2.number().optional().describe("Weight in kg.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const name = input.name.trim();
    const phone = input.phone.replace(/\D/g, "");
    if (!name) return { content: [{ type: "text", text: "Name is required" }], isError: true };
    if (phone.length !== 10)
      return {
        content: [{ type: "text", text: "Phone must be exactly 10 digits" }],
        isError: true
      };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("admissions").insert({
      user_id: ctx.getUserId(),
      name,
      phone,
      join_date: input.join_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      age: input.age ?? null,
      height: input.height ?? null,
      weight: input.weight ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added member ${data.name} (${data.phone}).` }],
      structuredContent: { member: data }
    };
  }
});

// src/lib/mcp/tools/record-payment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var record_payment_default = defineTool3({
  name: "record_payment",
  title: "Record membership payment",
  description: "Record a membership payment for one of the signed-in gym owner's members and mark that member as paid.",
  inputSchema: {
    member_id: z3.string().describe("The member's admission id (UUID) from list_members."),
    amount: z3.number().describe("Payment amount collected."),
    method: z3.string().optional().describe("Payment method, e.g. cash or upi. Defaults to cash."),
    payment_date: z3.string().optional().describe("Payment date as YYYY-MM-DD. Defaults to today."),
    notes: z3.string().optional().describe("Optional note about this payment.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!(input.amount > 0))
      return { content: [{ type: "text", text: "Amount must be greater than 0" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: member, error: memberError } = await supabase.from("admissions").select("id, name").eq("id", input.member_id).maybeSingle();
    if (memberError)
      return { content: [{ type: "text", text: memberError.message }], isError: true };
    if (!member)
      return { content: [{ type: "text", text: "Member not found" }], isError: true };
    const { data, error } = await supabase.from("payments").insert({
      user_id: ctx.getUserId(),
      admission_id: member.id,
      amount: input.amount,
      method: input.method ?? "cash",
      payment_date: input.payment_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    await supabase.from("admissions").update({ status: "paid" }).eq("id", member.id);
    return {
      content: [
        { type: "text", text: `Recorded ${input.amount} for ${member.name} and marked as paid.` }
      ],
      structuredContent: { payment: data }
    };
  }
});

// src/lib/mcp/tools/mark-attendance.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var mark_attendance_default = defineTool4({
  name: "mark_attendance",
  title: "Mark member attendance",
  description: "Check a member in for a given day (defaults to today) for the signed-in gym owner.",
  inputSchema: {
    member_id: z4.string().describe("The member's admission id (UUID) from list_members."),
    check_in_date: z4.string().optional().describe("Check-in date as YYYY-MM-DD. Defaults to today."),
    notes: z4.string().optional().describe("Optional note for this check-in.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("attendance").insert({
      user_id: ctx.getUserId(),
      admission_id: input.member_id,
      check_in_date: input.check_in_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Checked in on ${data.check_in_date}.` }],
      structuredContent: { attendance: data }
    };
  }
});

// src/lib/mcp/tools/gym-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var gym_summary_default = defineTool5({
  name: "gym_summary",
  title: "Gym overview summary",
  description: "Summarize the signed-in gym owner's gym: total members, paid vs unpaid counts, revenue collected, and check-ins over a recent window.",
  inputSchema: {
    days: z5.number().int().optional().describe("Window in days for revenue and attendance totals (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const window = Math.min(Math.max(days ?? 30, 1), 365);
    const since = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const [members, payments, checkIns] = await Promise.all([
      supabase.from("admissions").select("id, status"),
      supabase.from("payments").select("amount, payment_date").gte("payment_date", since),
      supabase.from("attendance").select("id, check_in_date").gte("check_in_date", since)
    ]);
    const firstError = members.error ?? payments.error ?? checkIns.error;
    if (firstError)
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    const all = members.data ?? [];
    const paid = all.filter((m) => m.status === "paid").length;
    const summary = {
      window_days: window,
      total_members: all.length,
      paid_members: paid,
      unpaid_members: all.length - paid,
      revenue_in_window: (payments.data ?? []).reduce((sum, p) => sum + Number(p.amount ?? 0), 0),
      payments_in_window: payments.data?.length ?? 0,
      check_ins_in_window: checkIns.data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cyyaltxyfuqrzhxtsnbt";
var mcp_default = defineMcp({
  name: "gym-aap",
  title: "gym aap",
  version: "0.1.0",
  instructions: "Tools for a gym owner's management app. Use `gym_summary` for an overview of members, revenue and check-ins; `list_members` to find members and their paid/unpaid status; `add_member` to register a new member; `record_payment` to collect a membership payment; `mark_attendance` to check a member in. All tools act as the signed-in gym owner and only see that owner's data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    gym_summary_default,
    list_members_default,
    add_member_default,
    record_payment_default,
    mark_attendance_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
